module.exports = {
    AUTH_NEW_OK: 0,
    AUTH_NOT_FOUND: 1,
    AUTH_PWD_MISMATCH: 2,
    AUTH_DUPLICATE: 3,
    AUTH_NOT_VERIFIED: 4,
    WAITING_NEW_OK: 5,
    WAITING_NOT_FOUND: 6,
    WAITING_DUPLICATE: 7
};